DELETE FROM comments;
DELETE FROM compilations_events;
DELETE FROM compilations;
DELETE FROM requests;
DELETE FROM events;
DELETE FROM categories;
DELETE FROM users;
DELETE FROM locations;

ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;
ALTER TABLE compilations ALTER COLUMN id RESTART WITH 1;
ALTER TABLE requests ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN id RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE locations ALTER COLUMN id RESTART WITH 1;



